apiVersion: apps/v1
kind: Deployment
metadata:
  name: anomaly-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anomaly-detection
  template:
    metadata:
      labels:
        app: anomaly-detection
    spec:
      containers:
      - image: discoverylabacr2.azurecr.io/consumer-insights-anomaly-detection:1.0
        imagePullPolicy: IfNotPresent
        name: anomaly-detection
        
---
apiVersion: v1
kind: Service
metadata:
  name: anomaly-detection
  labels:
    app: anomaly-detection
spec:
  type: NodePort
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    app: anomaly-detection
