apiVersion: v1
kind: Service
metadata:
  name: anomaly-detection
  labels:
    app: anomaly-detection
spec:
  type: NodePort
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    app: anomaly-detection